# Generated by Django 2.0 on 2019-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mistake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_content', models.CharField(max_length=225)),
                ('mistake_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
