# Generated by Django 2.0 on 2019-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_mistake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='mistake_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
