# Generated by Django 2.0 on 2019-08-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20190826_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='journal1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_name', models.CharField(max_length=225)),
                ('journal_action', models.CharField(max_length=225)),
                ('journal_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
