# Generated by Django 2.0 on 2019-08-28 10:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_journal1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            managers=[
                ('a_m', django.db.models.manager.Manager()),
            ],
        ),
    ]
