# Generated by Django 2.0 on 2019-08-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_student'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
    ]
