# Generated by Django 2.0 on 2019-11-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goods_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lan_various',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Design_code', models.CharField(max_length=225)),
                ('Image_path', models.CharField(max_length=225)),
                ('inventory', models.IntegerField()),
                ('unit_price', models.CharField(max_length=225)),
                ('Season_label', models.CharField(max_length=225)),
                ('putaway', models.CharField(max_length=225)),
                ('item_link', models.CharField(max_length=500)),
                ('zk_final_price', models.CharField(max_length=225)),
                ('title', models.CharField(max_length=225)),
                ('commission_rate', models.CharField(max_length=225)),
                ('coupon_info', models.CharField(max_length=225)),
                ('volume', models.CharField(max_length=225)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('product_description', models.TextField()),
                ('status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='lan_various_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_code', models.CharField(max_length=225)),
                ('color_specifications', models.CharField(max_length=225)),
                ('Stock_Quantity', models.IntegerField()),
                ('variouss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.lan_various')),
            ],
        ),
        migrations.CreateModel(
            name='lan_various_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=225)),
                ('img_path', models.CharField(max_length=225)),
                ('various_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.lan_various')),
            ],
        ),
        migrations.CreateModel(
            name='links_convert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('coupon_click_url', models.CharField(max_length=225)),
                ('coupon_end_time', models.CharField(max_length=225)),
                ('coupon_info', models.CharField(max_length=225)),
                ('coupon_remain_count', models.CharField(max_length=225)),
                ('coupon_start_time', models.CharField(max_length=225)),
                ('coupon_total_count', models.CharField(max_length=225)),
                ('coupon_type', models.CharField(max_length=225)),
                ('commission_rate', models.CharField(max_length=225)),
                ('num_iid', models.CharField(max_length=225)),
                ('tbk_pwd', models.CharField(max_length=225)),
                ('coupon_short_url', models.CharField(max_length=225)),
                ('request_time', models.CharField(max_length=225)),
                ('user_name', models.CharField(max_length=225)),
                ('my_tb_link', models.CharField(max_length=500)),
                ('adzone_id', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tb_paid_time', models.CharField(max_length=225)),
                ('tk_paid_time', models.CharField(max_length=225)),
                ('pay_price', models.CharField(max_length=225)),
                ('pub_share_fee', models.CharField(max_length=225)),
                ('trade_id', models.CharField(max_length=225)),
                ('tk_order_role', models.CharField(max_length=225)),
                ('tk_earning_time', models.CharField(max_length=225)),
                ('adzone_id', models.CharField(max_length=225)),
                ('pub_share_rate', models.CharField(max_length=225)),
                ('refund_tag', models.CharField(max_length=225)),
                ('subsidy_rate', models.CharField(max_length=225)),
                ('tk_total_rate', models.CharField(max_length=225)),
                ('item_category_name', models.CharField(max_length=225)),
                ('seller_nick', models.CharField(max_length=225)),
                ('pub_id', models.CharField(max_length=225)),
                ('alimama_rate', models.CharField(max_length=225)),
                ('subsidy_type', models.CharField(max_length=225)),
                ('item_img', models.CharField(max_length=225)),
                ('pub_share_pre_fee', models.CharField(max_length=225)),
                ('alipay_total_price', models.CharField(max_length=225)),
                ('item_title', models.CharField(max_length=225)),
                ('site_name', models.CharField(max_length=225)),
                ('item_num', models.IntegerField()),
                ('subsidy_fee', models.CharField(max_length=225)),
                ('alimama_share_fee', models.CharField(max_length=225)),
                ('trade_parent_id', models.CharField(max_length=225)),
                ('order_type', models.CharField(max_length=225)),
                ('tk_create_time', models.CharField(max_length=225)),
                ('flow_source', models.CharField(max_length=225)),
                ('terminal_type', models.CharField(max_length=225)),
                ('click_time', models.CharField(max_length=225)),
                ('tk_status', models.CharField(max_length=225)),
                ('item_price', models.CharField(max_length=225)),
                ('item_id', models.CharField(max_length=225)),
                ('adzone_name', models.CharField(max_length=225)),
                ('total_commission_rate', models.CharField(max_length=225)),
                ('item_link', models.CharField(max_length=225)),
                ('site_id', models.CharField(max_length=225)),
                ('seller_shop_title', models.CharField(max_length=225)),
                ('income_rate', models.CharField(max_length=225)),
                ('total_commission_fee', models.CharField(max_length=225)),
                ('tk_commission_pre_fee_for_media_platform', models.CharField(max_length=225)),
                ('tk_commission_fee_for_media_platform', models.CharField(max_length=225)),
                ('tk_commission_rate_for_media_platform', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='tbaok_anzone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=225)),
                ('adzone_name', models.CharField(max_length=225)),
                ('platform', models.CharField(max_length=225)),
                ('account_name', models.CharField(max_length=225)),
                ('adzone_id', models.CharField(max_length=225)),
                ('status', models.CharField(default='0', max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='goods_video',
            name='video_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.lan_various'),
        ),
    ]
