# Generated by Django 2.0 on 2019-08-12 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actor_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_numbers', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_section', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_title', models.CharField(max_length=225)),
                ('script_content', models.TextField()),
                ('upload_time', models.DateField()),
                ('author', models.CharField(max_length=225)),
                ('Script_usage', models.IntegerField(default=0)),
                ('play_actor_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.actor_number')),
                ('play_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.age')),
                ('play_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.content')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position_type', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='product_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_options', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='script_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_types', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_option', models.CharField(max_length=225)),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='play_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.position'),
        ),
        migrations.AddField(
            model_name='play',
            name='play_product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.product_option'),
        ),
        migrations.AddField(
            model_name='play',
            name='play_script_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.script_type'),
        ),
        migrations.AddField(
            model_name='play',
            name='play_sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.sex'),
        ),
    ]
