# Generated by Django 2.0 on 2019-08-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
