# Generated by Django 2.0 on 2019-08-12 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='approved_memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_user', models.CharField(max_length=255)),
                ('audit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=255)),
                ('product_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=255)),
                ('vid', models.IntegerField(default='0')),
                ('task_status', models.CharField(default='未提交视频', max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.play')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.product')),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_path', models.CharField(max_length=255)),
                ('video_product', models.CharField(max_length=255)),
                ('video_author', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='approved_memo',
            name='tid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.task'),
        ),
    ]
